apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: h53hnx3ph-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: h53hnx3ph-nodejs 
  name: h53hnx3ph-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: h53hnx3ph-nodejs 
